### ISSUE TITLE
Update runner to Py3

### ISSUE THREAD

**Issue by hillaryj** [cisagov/cyhy-runner#1]
# 🚀 Feature Proposal

Update cyhy-runner to python3.

## Motivation

The repo needs to be updated to be as Python 3 compatible as possible. We are dropping support for Python 2 completely in the near future.

**Comment by mcdonnnj** [comment]
The job pushed to `vulnscan` instances is a Python script that must be updated to Python 3 before the migration of this project can be finalized. Please see https://github.com/jsf9k/cyhy-commander/issues/15 for more information.
